[theme]
base                     = "dark"
primaryColor             = "#7c3aed"
backgroundColor          = "#080c18"
secondaryBackgroundColor = "#0f1426"
textColor                = "#e2e8f0"
font                     = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
